name: Create GKE cluster

on:
  workflow_dispatch:

jobs:
  create-gke:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/.gcp.json
    runs-on: ubuntu-latest
    steps:
    - name: Get the source code
      uses: actions/checkout@v2

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GAR_JSON_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: expose GCP creds as file
      run: 'echo "$GAR_JSON" > "$GOOGLE_APPLICATION_CREDENTIALS"'
      shell: bash
      env:
        GAR_JSON: ${{secrets.GAR_JSON_KEY}}

    - name: Plan
      run: |
        cd ${GITHUB_WORKSPACE}/src
        terraform init
        terraform fmt
        terraform validate
        terraform plan

    - name: Apply
      run: |
        # gcloud info
        cd ${GITHUB_WORKSPACE}/src
        terraform apply -auto-approve
        rm -f $GOOGLE_APPLICATION_CREDENTIALS

