name: NGINX Ingress controller

on:
  workflow_dispatch:

jobs:

  create-ingress:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/.gcp.json
    runs-on: ubuntu-latest
    steps:
    - name: Get the source code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_CLUSTER_ADMIN }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0.4.0'
      with:
        cluster_name: 'dev'
        location: 'us-west2-a'
    - name: Install Ingress Controller
      run: |
        $GITHUB_WORKSPACE/scripts/install-nginx-ingress.sh
